version: '3.8'  
services:  
    web:  
        container_name: my-angular-app-container  
        build:  
            context: .  
            dockerfile: Dockerfile  
        ports:
            - "80:80"